variable "project" {}
variable "vpc_id" {}
variable "instance_web" {}
variable "db_storage_size" {}
variable "db_engine_version" {}
variable "db_instance_class" {}
variable "db_name" {}
variable "db_user" {}
variable "db_password" {}
variable "db_parameter_group" {}
variable "private-subnets" {}
variable "sg_web" {}
