name: pr-tfsec

on: [push]

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: tfsec
        uses: reviewdog/action-tfsec@master
        with:
          fail_on_error: "true"
          filter_mode: "nofilter"
